name: Multi-Labeler

on:
  issues:
    types: [opened]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Label Issue
        uses: actions/github-script@v0.11.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const labels = ['status: to do', 'priority: high'];
            const issueNumber = context.issue.number;
            const octokit = new github.GitHub(GITHUB_TOKEN);
            octokit.issues.addLabels({ owner: context.repo.owner, repo: context.repo.repo, issue_number: issueNumber, labels: labels});
