name: Custom Directory-Based Labeler

on:
  pull_request:
    types: [opened]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Label Pull Request
        uses: actions/labeler@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:

          # The list of file paths and labels to apply if a file in the specified path was changed
          file_labels: |
            src/                area: src
            root/               area: root
            package/                area: package

